[package]
name = "gameoflife_cli"
description = "Conway's Game of Life running in a terminal window"
version = "0.2.0"
authors = ["Maxwell Anderson <maxwell.brayden.anderson@gmail.com>"]
edition = "2018"
repository = "https://github.com/Maxgy/gameoflife-cli"
license = "MIT"

[dependencies]
rand = "0.7"
term_size = "0.3"
termion = "1.5"